version: "3"

services:
    haproxy:
        image: haproxy:1.8.14-alpine
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        container_name: haproxy
        ports:
            - "8080:80"
        restart: always

    default-service:
        build: ./
        image: httpd:2.4.37-alpine  #Since this is built with dockerfile, this is redundant, 
                                    #but i left it because this is also image name. Otherwise image will be named after folder.
                                    #Image name being the image value shown with "docker ps -a" command.
        container_name: default-service
        restart: always

    apache-service-1:
        
        build: ./ #Since image has to be built and based on Dockerfile. "image: httpd:2.4.37-alpine" would work the smae in this instance.
        image: httpd:2.4.37-alpine #for the image name.
        volumes:
            - ./service-html/index-service-1.html:/usr/local/apache2/htdocs/index.html:ro
        container_name: apache-service-1
        restart: always
        
    apache-service-2:
        build: ./ #Since image has to be built and based on Dockerfile.
        image: httpd:2.4.37-alpine #for the image name.
        volumes:
            - ./service-html/index-service-2.html:/usr/local/apache2/htdocs/index.html:ro
        container_name: apache-service-2
        ports:
            - "8282:80"
        restart: always




    







