version: "3"

services:

    haproxy:
        image: haproxy:1.8.14-alpine
        volumes:
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        links:
            - service-1
            - service-2
            - default-service
        container_name: haproxy
        ports:
            - "8080:80"

    service-1:
        image: dockercloud/hello-world
        container_name: service-1



    service-2:
        image: dockercloud/hello-world
        container_name: service-2
        ports:

            - "8282:80"

    default-service:
        build: ./
        container_name: default-service
        restart: always







